apiVersion: v2
name: pagopa-nodo-cfg-data-migration
description: A microservice that permits the migration from Nexi's Oracle database to PagoPA's PostgreSQL database
type: application
version: 0.55.0
appVersion: 0.1.0-19-dev
dependencies:
  - name: microservice-chart
    version: 2.8.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
