microservice-chart:
  namespace: "nodo"
  nameOverride: ""
  fullnameOverride: ""
  image:
    repository: ghcr.io/pagopa/pagopa-nodo-cfg-data-migration
    tag: "0.1.0-22-dev"
    pullPolicy: Always
  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 180
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 180
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
  service:
    create: true
    type: ClusterIP
    ports:
      - 8080
  ingress:
    create: true
    host: "weudev.nodo.internal.dev.platform.pagopa.it"
    path: /datamigration/(.*)
    servicePort: 8080
  serviceAccount:
    create: false
    annotations: {}
    name: ""
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: "1Gi"
      cpu: "0.40"
    limits:
      memory: "1Gi"
      cpu: "0.5"
  autoscaling:
    enable: true
    minReplica: 1
    maxReplica: 1
    pollingInterval: 10 # seconds
    cooldownPeriod: 50 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "75"
  envConfig:
    WEBSITE_SITE_NAME: 'pagopanodocfgdatamigration'
    ENV: 'Azure Kubernetes'
    ORACLEDB_CONNECTION_STRING: "jdbc:oracle:thin:@(DESCRIPTION=(ENABLE=BROKEN)(ADDRESS=(PROTOCOL=tcp)(PORT=1522)(HOST=db-nodo-pagamenti.d.db-nodo-pagamenti.com))(CONNECT_DATA=(SERVICE_NAME=NDPSPCT_PP_NODO4_CFG))(SO_KEEPALIVE=true)(TCP_KEEPIDLE=60)(TCP_KEEPINTVL=30)(TCP_KEEPCNT=15))"
    ORACLEDB_USERNAME: "NODO4_CFG"
    ORACLEDB_DEFAULT_SCHEMA: "NODO4_CFG"
    POSTGRESQL_CONNECTION_STRING: "jdbc:postgresql://pagopa-d-weu-nodo-flexible-postgresql.postgres.database.azure.com:6432/nodo?sslmode=require&prepareThreshold=0&currentSchema=cfg"
    POSTGRESQL_USERNAME: "cfg"
    POSTGRESQL_DEFAULT_SCHEMA: "cfg"
    POSTGRESQL_JDBC_BATCH_SIZE: '30'
    DEFAULT_LOGGING_LEVEL: "INFO"
    APP_LOGGING_LEVEL: "INFO"
    SQL_LOGGING_LEVEL: "INFO"
    SQL_BINDER_LOGGING_LEVEL: "INFO"
    CORS_CONFIGURATION: '{"origins": ["*"], "methods": ["*"]}'
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.elastic-system.svc:4317"
    # Variables for define batch size for all steps
    STEP_BINARYFILE_BATCH_SIZE: '100'
    STEP_CANALETIPOVERSAMENTO_BATCH_SIZE: '1000'
    STEP_CANALINODO_BATCH_SIZE: '1000'
    STEP_CANALI_BATCH_SIZE: '1000'
    STEP_CDIDETAIL_BATCH_SIZE: '1000'
    STEP_CDIFASCIA_BATCH_SIZE: '1000'
    STEP_CDIINFORMAZIONISERVIZIO_BATCH_SIZE: '1000'
    STEP_CDIMASTER_BATCH_SIZE: '1000'
    STEP_CDIPREFERENCES_BATCH_SIZE: '1000'
    STEP_CDSCATEGORIE_BATCH_SIZE: '1000'
    STEP_CDSSERVIZIO_BATCH_SIZE: '1000'
    STEP_CDSSOGGETTOSERVIZIO_BATCH_SIZE: '1000'
    STEP_CDSSOGGETTO_BATCH_SIZE: '1000'
    STEP_CODIFICHEPA_BATCH_SIZE: '1000'
    STEP_CODIFICHE_BATCH_SIZE: '1000'
    STEP_CONFIGURATIONKEYS_BATCH_SIZE: '1000'
    STEP_DIZIONARIOMETADATI_BATCH_SIZE: '1000'
    STEP_ELENCOSERVIZI_BATCH_SIZE: '1000'
    STEP_FTPSERVERS_BATCH_SIZE: '1000'
    STEP_GDECONFIG_BATCH_SIZE: '1000'
    STEP_INFORMATIVECONTOACCREDITODETAIL_BATCH_SIZE: '1000'
    STEP_INFORMATIVECONTOACCREDITOMASTER_BATCH_SIZE: '1000'
    STEP_INFORMATIVEPADETAIL_BATCH_SIZE: '1000'
    STEP_INFORMATIVEPAFASCE_BATCH_SIZE: '1000'
    STEP_INFORMATIVEPAMASTER_BATCH_SIZE: '1000'
    STEP_INTERMEDIARIPA_BATCH_SIZE: '1000'
    STEP_INTERMEDIARIPSP_BATCH_SIZE: '1000'
    STEP_PASTAZIONEPA_BATCH_SIZE: '1000'
    STEP_PA_BATCH_SIZE: '1000'
    STEP_PDD_BATCH_SIZE: '1000'
    STEP_PSPCANALETIPOVERSAMENTO_BATCH_SIZE: '1000'
    STEP_PSP_BATCH_SIZE: '1000'
    STEP_QUADRATURESCHED_BATCH_SIZE: '1000'
    STEP_STAZIONI_BATCH_SIZE: '1000'
    STEP_TIPIVERSAMENTO_BATCH_SIZE: '1000'
    STEP_WFESPPLUGINCONF_BATCH_SIZE: '1000'
  envSecret:
    ORACLEDB_PASSWORD: 'oracle-db-cfg-password'
    POSTGRESQL_PASSWORD: 'db-cfg-password'
    OTEL_AUTH_BEARER: "otel-auth-bearer"
  keyvault:
    name: "pagopa-d-nodo-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations: []
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
  canaryDelivery:
    create: false
